In [30]:
import torch as th
import numpy as np

In [2]:
dtype = th.float64

gpuid = 0
#device = th.device("cuda:"+ str(gpuid))
device = th.device("cpu")

print("Execution device: ",device)
print("PyTorch version: ", th.__version__ )
print("CUDA available: ", th.cuda.is_available())
print("CUDA version: ", th.version.cuda)
print("CUDA device:", th.cuda.get_device_name(gpuid))

Execution device:  cpu
PyTorch version:  0.4.1
CUDA available:  True
CUDA version:  9.0.176
CUDA device: TITAN V


In [114]:
def f(x, a, b):
    return (x[0]+a)**2 + b*x[1]**2 

In [146]:
x = th.tensor([1,2], device=device, dtype=dtype, requires_grad=True)
x

tensor([ 1.,  2.], dtype=torch.float64)

In [147]:
a=2;
b=0.2;

In [148]:
f(x,a,b)

tensor(9.8000, dtype=torch.float64)

In [149]:
optimizer = th.optim.LBFGS([x])

In [150]:
for i in range(10):
    optimizer.zero_grad()
    loss = f(x,a,b)
    loss.backward()
    def closure():
        return f(x,a,b)
    optimizer.step(closure)
    print('step: {} f: {} gradNorm: {}'.format(i, loss, th.norm(x.grad)))

step: 0 f: 9.8 gradNorm: 6.053098380168622
step: 1 f: 12553.132844290656 gradNorm: 223.8281062653331
step: 2 f: 25.226117090916397 gradNorm: 9.927009212605501
step: 3 f: 0.20544274555982303 gradNorm: 0.4081460328968292
step: 4 f: 0.12998960554489497 gradNorm: 0.3267184662233951
step: 5 f: 2.7500359035320023e-11 gradNorm: 1.0483980147394509e-05
step: 6 f: 2.481946223445147e-11 gradNorm: 9.959859255387119e-06
step: 7 f: 2.239991502710887e-11 gradNorm: 9.46194050277711e-06
step: 8 f: 2.239991502710887e-11 gradNorm: 9.46194050277711e-06
step: 9 f: 2.239991502710887e-11 gradNorm: 9.46194050277711e-06


In [129]:
x.grad

tensor(1.00000e-06 *
       [ 9.4610, -0.1335], dtype=torch.float64)

In [130]:
x

tensor([-2.0000e+00, -3.3387e-07], dtype=torch.float64)

In [99]:
print('step: {} f: {} grad: {} x: {} '.format(i, f(x), x.grad, x))

f = 3.4905387467562244e-13


In [143]:
th.norm(x.grad)

tensor(1.00000e-06 *
       9.4619, dtype=torch.float64)

In [3]:
A = th.tensor([[1,0,0],[2,3,0],[4,5,6]])
A

tensor([[1, 0, 0],
        [2, 3, 0],
        [4, 5, 6]])

In [20]:
th.einsum('ij->', (A,))

tensor(21)

In [22]:
th.tril(A,-1)

tensor([[0, 0, 0],
        [2, 0, 0],
        [4, 5, 0]])

In [23]:
1/A

tensor([[                   1, -9223372036854775808, -9223372036854775808],
        [                   0,                    0, -9223372036854775808],
        [                   0,                    0,                    0]])

In [44]:
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [75]:
n=3
A = np.zeros((2,n,n))
for i in range(2):
    A[i][np.tril_indices(n)]=a[i,:]

A = th.from_numpy(A)
A

tensor([[[ 1.,  0.,  0.],
         [ 2.,  3.,  0.],
         [ 4.,  5.,  6.]],

        [[ 7.,  0.,  0.],
         [ 8.,  9.,  0.],
         [10., 11., 12.]]], dtype=torch.float64)

In [96]:
A2= th.matmul(A,th.transpose(A, 1, 2))
A2

tensor([[[  1.,   2.,   4.],
         [  2.,  13.,  23.],
         [  4.,  23.,  77.]],

        [[ 49.,  56.,  70.],
         [ 56., 145., 179.],
         [ 70., 179., 365.]]], dtype=torch.float64)

In [71]:
dA=th.diagonal(A, offset=0, dim1=-1, dim2=-2)
dA

tensor([[ 1.,  3.,  6.],
        [ 7.,  9., 12.]], dtype=torch.float64)

In [78]:
detA = th.abs(th.prod(th.diagonal(A, offset=0, dim1=-1, dim2=-2),1))
detA

tensor([ 18., 756.], dtype=torch.float64)

In [80]:
B = th.matmul(A,th.transpose(A, 1, 2))[0,:,:]
B

tensor([[ 1.,  2.,  4.],
        [ 2., 13., 23.],
        [ 4., 23., 77.]], dtype=torch.float64)

In [90]:
C = th.matmul(A,th.transpose(A, 1, 2))[1,:,:]
C

tensor([[ 49.,  56.,  70.],
        [ 56., 145., 179.],
        [ 70., 179., 365.]], dtype=torch.float64)

In [86]:
P = th.tensor([[0,0,1],[1,0,0],[0,1,0]], dtype=dtype)
P

tensor([[0., 0., 1.],
        [1., 0., 0.],
        [0., 1., 0.]], dtype=torch.float64)

In [94]:
th.inverse(C + P@B@th.t(P))

tensor([[ 0.0101, -0.0026, -0.0012],
        [-0.0026,  0.0175, -0.0078],
        [-0.0012, -0.0078,  0.0067]], dtype=torch.float64)

In [95]:
th.inverse(C + B)

tensor([[ 0.0348, -0.0128,  0.0000],
        [-0.0128,  0.0199, -0.0070],
        [ 0.0000, -0.0070,  0.0054]], dtype=torch.float64)

In [97]:
th.matmul(P,th.transpose(A2, 1, 2))

tensor([[[  4.,  23.,  77.],
         [  1.,   2.,   4.],
         [  2.,  13.,  23.]],

        [[ 70., 179., 365.],
         [ 49.,  56.,  70.],
         [ 56., 145., 179.]]], dtype=torch.float64)

In [99]:
A2

tensor([[[  1.,   2.,   4.],
         [  2.,  13.,  23.],
         [  4.,  23.,  77.]],

        [[ 49.,  56.,  70.],
         [ 56., 145., 179.],
         [ 70., 179., 365.]]], dtype=torch.float64)

In [101]:
th.rsqrt(A2)

tensor([[[1.0000, 0.7071, 0.5000],
         [0.7071, 0.2774, 0.2085],
         [0.5000, 0.2085, 0.1140]],

        [[0.1429, 0.1336, 0.1195],
         [0.1336, 0.0830, 0.0747],
         [0.1195, 0.0747, 0.0523]]], dtype=torch.float64)

In [102]:
C

tensor([[ 49.,  56.,  70.],
        [ 56., 145., 179.],
        [ 70., 179., 365.]], dtype=torch.float64)

In [103]:
B

tensor([[ 1.,  2.,  4.],
        [ 2., 13., 23.],
        [ 4., 23., 77.]], dtype=torch.float64)

In [106]:
th.add(A2,A2)

tensor([[[  2.,   4.,   8.],
         [  4.,  26.,  46.],
         [  8.,  46., 154.]],

        [[ 98., 112., 140.],
         [112., 290., 358.],
         [140., 358., 730.]]], dtype=torch.float64)

In [107]:
2*A2

tensor([[[  2.,   4.,   8.],
         [  4.,  26.,  46.],
         [  8.,  46., 154.]],

        [[ 98., 112., 140.],
         [112., 290., 358.],
         [140., 358., 730.]]], dtype=torch.float64)

In [115]:
th.potri(th.potrf(A2[0], upper=False), upper=False)

tensor([[ 1.4568, -0.1914, -0.0185],
        [-0.1914,  0.1883, -0.0463],
        [-0.0185, -0.0463,  0.0278]], dtype=torch.float64)

In [129]:
A_LU, piv = th.btrifact(A2, pivot=True)
A_LU

tensor([[[   4.0000,   23.0000,   77.0000],
         [   0.2500,   -3.7500,  -15.2500],
         [   0.5000,   -0.4000,  -21.6000]],

        [[  70.0000,  179.0000,  365.0000],
         [   0.7000,  -69.3000, -185.5000],
         [   0.8000,   -0.0260, -117.8182]]], dtype=torch.float64)

In [125]:
th.det(A2[1])

tensor(571536., dtype=torch.float64)

In [137]:
th.prod(th.diag(A_LU[1]))


tensor(571536., dtype=torch.float64)

In [142]:
th.where(A >0, th.rsqrt(A), A)

tensor([[[1.0000, 0.0000, 0.0000],
         [0.7071, 0.5774, 0.0000],
         [0.5000, 0.4472, 0.4082]],

        [[0.3780, 0.0000, 0.0000],
         [0.3536, 0.3333, 0.0000],
         [0.3162, 0.3015, 0.2887]]], dtype=torch.float64)

In [148]:
A=th.tensor([[1,2],[3,4]],dtype=dtype)
A

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [152]:
A@th.ones_like(A)@th.t(A)

tensor([[ 9., 21.],
        [21., 49.]], dtype=torch.float64)

In [153]:
A2

tensor([[[  1.,   2.,   4.],
         [  2.,  13.,  23.],
         [  4.,  23.,  77.]],

        [[ 49.,  56.,  70.],
         [ 56., 145., 179.],
         [ 70., 179., 365.]]], dtype=torch.float64)

In [154]:
L = [[0.0] * len(A) for _ in range(len(A))]

In [155]:
L

[[0.0, 0.0], [0.0, 0.0]]

In [171]:
for i in range(2):
    for j in range(i,2):
        print(int((i+1)*(j+1) - 1))
    

0
1
3


In [172]:
B = th.ones_like(A2)
B

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]], dtype=torch.float64)

In [175]:
th.sum(B, (1,2))

tensor([9., 9.], dtype=torch.float64)