In [1]:
import numpy as np
import torch

import time

print("PyTorch version: ", torch.__version__ )
print("CUDA available: ", torch.cuda.is_available())
print("CUDA version: ", torch.version.cuda)

PyTorch version:  1.1.0
CUDA available:  True
CUDA version:  10.0.130


In [2]:
#np.random.seed(42)
n = 20000

In [3]:
A = np.random.randn(n,n).astype('float64')
B = np.random.randn(n,n).astype('float64')

In [4]:
start_time = time.time()
nrm = np.linalg.norm(A@B)
print(" took {} seconds ".format(time.time() - start_time))
print(" norm = ",nrm)

 took 35.13306379318237 seconds 
 norm =  2828463.0201447452


In [5]:
tA = torch.randn(n,n, dtype = torch.float64)
tB = torch.randn(n,n, dtype = torch.float64)

In [6]:
start_time = time.time()
tnrm = (tA@tB).norm()
print(" took {} seconds ".format(time.time() - start_time))
print(" norm = ",tnrm)

 took 16.623844861984253 seconds 
 norm =  tensor(2828092.3386, dtype=torch.float64)


In [17]:
gA = torch.randn(n,n, device="cuda")
gB = torch.randn(n,n, device="cuda")

In [8]:
start_time = time.time()
gnrm = (gA@gB).norm()
print(" took {} seconds ".format(time.time() - start_time))
print(" norm = ",gnrm)

 took 0.17258548736572266 seconds 
 norm =  tensor(1.00000e+06 *
       1.0001, device='cuda:0')


In [9]:
A = np.random.randn(4,4).astype('float32')
X = np.random.randn(4,4).astype('float32')

In [10]:
A

array([[-0.5049461 , -0.19887437,  0.18442628, -0.68315524],
       [-0.9890729 , -0.8097865 , -0.17070463, -0.24591489],
       [ 1.0504804 ,  2.2784846 , -0.61209446,  0.8285161 ],
       [ 1.1353166 , -0.01387051,  0.11121433, -0.93461305]],
      dtype=float32)

In [11]:
X

array([[-0.79756254,  0.17181225, -0.96386087,  0.3195454 ],
       [ 0.13475977, -0.10574374,  1.1533258 ,  0.6280106 ],
       [-0.5517436 ,  0.81820333,  0.34025642,  1.4709991 ],
       [ 0.20693423, -2.212612  ,  0.38112938,  0.67755526]],
      dtype=float32)

In [12]:
np.linalg.norm(A@X)

4.967725

In [13]:
nrmAX = np.sqrt(np.trace(np.transpose(A@X)@(A@X)))
nrmAX

4.9677243

In [74]:
tA = torch.tensor(A, requires_grad=True)
tA

tensor([[-0.5049, -0.1989,  0.1844, -0.6832],
        [-0.9891, -0.8098, -0.1707, -0.2459],
        [ 1.0505,  2.2785, -0.6121,  0.8285],
        [ 1.1353, -0.0139,  0.1112, -0.9346]])

In [75]:
tX = torch.tensor(X, requires_grad=True)
tX

tensor([[-0.7976,  0.1718, -0.9639,  0.3195],
        [ 0.1348, -0.1057,  1.1533,  0.6280],
        [-0.5517,  0.8182,  0.3403,  1.4710],
        [ 0.2069, -2.2126,  0.3811,  0.6776]])

In [76]:
nrmtAX = (tA@tX).norm()
nrmtAX

tensor(4.9677)

In [77]:
dnrmAX = (A.transpose()@A@X)/nrmAX
dnrmAX

array([[-0.42761004, -0.19405963,  0.05810442,  0.5713776 ],
       [-0.1298413 , -1.2209185 ,  0.8133703 ,  0.8767274 ],
       [-0.04326902,  0.39604086, -0.23749249, -0.1535332 ],
       [ 0.1609802 , -1.0779235 ,  0.55445796,  0.38704368]],
      dtype=float32)

In [78]:
torch.autograd.grad(nrmtAX, tX)

(tensor([[-0.4276, -0.1941,  0.0581,  0.5714],
         [-0.1298, -1.2209,  0.8134,  0.8767],
         [-0.0433,  0.3960, -0.2375, -0.1535],
         [ 0.1610, -1.0779,  0.5545,  0.3870]]),)

In [55]:
nrmtAX.backward(tX)

In [57]:
dnrmtAX = tX.grad
dnrmtAX

tensor([[-0.0611, -1.6265,  0.0358,  0.5970],
        [-0.0055, -0.8895,  0.2976,  1.0967],
        [-0.0141,  0.1361, -0.0813, -0.2394],
        [ 0.0570,  0.6177,  0.2157,  0.4246]])

In [35]:
from torch.autograd import Variable

In [36]:
gA = Variable(tA.cuda(), requires_grad=True)
gA

tensor([[-0.5049, -0.1989,  0.1844, -0.6832],
        [-0.9891, -0.8098, -0.1707, -0.2459],
        [ 1.0505,  2.2785, -0.6121,  0.8285],
        [ 1.1353, -0.0139,  0.1112, -0.9346]], device='cuda:0')

In [23]:
nrmgA = gA.norm()
nrmgA

tensor(3.4713, device='cuda:0')

In [24]:
nrmgA.backward()

In [25]:
dnrmgA = gA.grad
dnrmgA




tensor([[-0.1455, -0.0573,  0.0531, -0.1968],
        [-0.2849, -0.2333, -0.0492, -0.0708],
        [ 0.3026,  0.6564, -0.1763,  0.2387],
        [ 0.3271, -0.0040,  0.0320, -0.2692]], device='cuda:0')

In [26]:
tA = torch.randn(2,2)
tA

tensor([[ 0.6154,  0.0762],
        [-0.9105,  0.3103]])

In [27]:
tI = torch.eye(3)
tI

tensor([[ 1.,  0.,  0.],
        [ 0.,  1.,  0.],
        [ 0.,  0.,  1.]])

In [28]:
np.kron(tA,tI)

array([[ 0.6153514 ,  0.        ,  0.        ,  0.07615926,  0.        ,
         0.        ],
       [ 0.        ,  0.6153514 ,  0.        ,  0.        ,  0.07615926,
         0.        ],
       [ 0.        ,  0.        ,  0.6153514 ,  0.        ,  0.        ,
         0.07615926],
       [-0.9105107 , -0.        , -0.        ,  0.3102524 ,  0.        ,
         0.        ],
       [-0.        , -0.9105107 , -0.        ,  0.        ,  0.3102524 ,
         0.        ],
       [-0.        , -0.        , -0.9105107 ,  0.        ,  0.        ,
         0.3102524 ]], dtype=float32)