In [1]:
import numpy as np
import torch as th


In [2]:
A=B=C=np.zeros((3,3))
print(A)
print(B)
print(C)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
vechLk = np.array([1,2,3,4,5,6])
Lk = np.zeros((3,3))
il = np.triu_indices(3)
Lk[il] = vechLk
Lk.T

array([[1., 0., 0.],
       [2., 4., 0.],
       [3., 5., 6.]])

In [4]:
Lk.T

array([[1., 0., 0.],
       [2., 4., 0.],
       [3., 5., 6.]])

In [5]:
Lk[1,1]

4.0

In [6]:
len(vechLk)

6

In [7]:
x = list(range(18))

In [8]:
x

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]

In [9]:
n = 3
nb = 3
nx = len(x);
nn = int(n*(n+1)/2);
print(n,nb,nx,nn)

3 3 18 6


In [10]:
for j in range(0,nb):
    for i in range(j,nb):
        aai = i*nn;
        aaj = j*nn;
        
        print(aai,aaj)
        
        vechLi = x[aai:aai+nn];
        vechLj = x[aaj:aaj+nn];
        
        print('vechLi',vechLi)
        print('vechLj',vechLj)

0 0
vechLi [0, 1, 2, 3, 4, 5]
vechLj [0, 1, 2, 3, 4, 5]
6 0
vechLi [6, 7, 8, 9, 10, 11]
vechLj [0, 1, 2, 3, 4, 5]
12 0
vechLi [12, 13, 14, 15, 16, 17]
vechLj [0, 1, 2, 3, 4, 5]
6 6
vechLi [6, 7, 8, 9, 10, 11]
vechLj [6, 7, 8, 9, 10, 11]
12 6
vechLi [12, 13, 14, 15, 16, 17]
vechLj [6, 7, 8, 9, 10, 11]
12 12
vechLi [12, 13, 14, 15, 16, 17]
vechLj [12, 13, 14, 15, 16, 17]


In [11]:
x[-nb:]

[15, 16, 17]

In [12]:
np.linalg.inv(Lk.T)

array([[ 1.00000000e+00,  0.00000000e+00,  1.85037171e-17],
       [-5.00000000e-01,  2.50000000e-01, -0.00000000e+00],
       [-8.33333333e-02, -2.08333333e-01,  1.66666667e-01]])

In [13]:
np.diag(1/np.diag(Lk))

array([[1.        , 0.        , 0.        ],
       [0.        , 0.25      , 0.        ],
       [0.        , 0.        , 0.16666667]])

In [14]:
Lk.T

array([[1., 0., 0.],
       [2., 4., 0.],
       [3., 5., 6.]])

In [15]:
def vech(A):
    count = 0
    c = A.shape[0]
    v = np.zeros(c * (c + 1) // 2,)
    for j in range(c):
        for i in range(j,c):
            v[count] = A[i,j]
            count += 1
    return v

def uvech(v,n):
    count = 0
    L = np.zeros((n,n))
    for j in range(n):
        for i in range(j,n):
            L[i,j]=v[count]
            count += 1
    return L

In [16]:
x = vech(Lk.T)
x

array([1., 2., 3., 4., 5., 6.])

In [17]:
uvech(x,3)

array([[1., 0., 0.],
       [2., 4., 0.],
       [3., 5., 6.]])

In [18]:
A = th.zeros((3,3))

In [19]:
A = th.tensor(Lk.T)

In [20]:
A

tensor([[ 1.,  0.,  0.],
        [ 2.,  4.,  0.],
        [ 3.,  5.,  6.]], dtype=torch.float64)

In [21]:
th.inverse(A)

tensor([[ 1.0000,  0.0000,  0.0000],
        [-0.5000,  0.2500,  0.0000],
        [-0.0833, -0.2083,  0.1667]], dtype=torch.float64)

In [22]:
th.det(A)

tensor(24.0000, dtype=torch.float64)

In [23]:
th.pow(th.sqrt(th.abs(th.det(A))), 4)

tensor(576.0000, dtype=torch.float64)

In [24]:
th.diag(th.diag(A))

tensor([[ 1.,  0.,  0.],
        [ 0.,  4.,  0.],
        [ 0.,  0.,  6.]], dtype=torch.float64)

In [25]:
vech(A)

array([1., 2., 3., 4., 5., 6.])

In [28]:
A.view(-1)

tensor([ 1.,  0.,  0.,  2.,  4.,  0.,  3.,  5.,  6.], dtype=torch.float64)