In [1]:
import numpy as np
import torch as th

In [2]:
A = th.ones((4,2,2))
A

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [3]:
for i in range(4): A[i]=A[i]*i
A

tensor([[[0., 0.],
         [0., 0.]],

        [[1., 1.],
         [1., 1.]],

        [[2., 2.],
         [2., 2.]],

        [[3., 3.],
         [3., 3.]]])

In [4]:
A*2

tensor([[[0., 0.],
         [0., 0.]],

        [[2., 2.],
         [2., 2.]],

        [[4., 4.],
         [4., 4.]],

        [[6., 6.],
         [6., 6.]]])

In [5]:
B = th.ones((2,2))*2
B

tensor([[2., 2.],
        [2., 2.]])

In [6]:
A@B

tensor([[[ 0.,  0.],
         [ 0.,  0.]],

        [[ 4.,  4.],
         [ 4.,  4.]],

        [[ 8.,  8.],
         [ 8.,  8.]],

        [[12., 12.],
         [12., 12.]]])

In [7]:
B*A@B

tensor([[[ 0.,  0.],
         [ 0.,  0.]],

        [[ 8.,  8.],
         [ 8.,  8.]],

        [[16., 16.],
         [16., 16.]],

        [[24., 24.],
         [24., 24.]]])

In [8]:
C = th.reshape(A,(2,2,2,2))
C

tensor([[[[0., 0.],
          [0., 0.]],

         [[1., 1.],
          [1., 1.]]],


        [[[2., 2.],
          [2., 2.]],

         [[3., 3.],
          [3., 3.]]]])

In [9]:
B*C@B

tensor([[[[ 0.,  0.],
          [ 0.,  0.]],

         [[ 8.,  8.],
          [ 8.,  8.]]],


        [[[16., 16.],
          [16., 16.]],

         [[24., 24.],
          [24., 24.]]]])

In [10]:
C@C

tensor([[[[ 0.,  0.],
          [ 0.,  0.]],

         [[ 2.,  2.],
          [ 2.,  2.]]],


        [[[ 8.,  8.],
          [ 8.,  8.]],

         [[18., 18.],
          [18., 18.]]]])

In [11]:
A@A

tensor([[[ 0.,  0.],
         [ 0.,  0.]],

        [[ 2.,  2.],
         [ 2.,  2.]],

        [[ 8.,  8.],
         [ 8.,  8.]],

        [[18., 18.],
         [18., 18.]]])

In [12]:
C

tensor([[[[0., 0.],
          [0., 0.]],

         [[1., 1.],
          [1., 1.]]],


        [[[2., 2.],
          [2., 2.]],

         [[3., 3.],
          [3., 3.]]]])

In [13]:
th.sum(th.diagonal(C, dim1=-2, dim2=-1), dim=-1, keepdim=False)

tensor([[0., 2.],
        [4., 6.]])

In [14]:
B = th.rand((4,2,2))

In [15]:
B.shape

torch.Size([4, 2, 2])

In [16]:
th.sum(th.diagonal(C, dim1=-2, dim2=-1), dim=-1, keepdim=False)

tensor([[0., 2.],
        [4., 6.]])

In [17]:
th.trace(B[1])

tensor(0.6071)

In [18]:
C

tensor([[[[0., 0.],
          [0., 0.]],

         [[1., 1.],
          [1., 1.]]],


        [[[2., 2.],
          [2., 2.]],

         [[3., 3.],
          [3., 3.]]]])

In [19]:
th.sum(C, dim=(-2,-1))

tensor([[ 0.,  4.],
        [ 8., 12.]])

In [20]:
AK = th.rand((2,2,2))
AL = th.rand((2,2,2))

In [21]:
th.matmul(AK,th.matmul(C,AL))

tensor([[[[0.0000, 0.0000],
          [0.0000, 0.0000]],

         [[1.0792, 1.0309],
          [1.1460, 1.0947]]],


        [[[2.2773, 2.8771],
          [3.1573, 3.9890]],

         [[3.2377, 3.0927],
          [3.4381, 3.2842]]]])

In [22]:
AK[1]@C[1,1]@AL[1]

tensor([[3.2377, 3.0927],
        [3.4381, 3.2842]])

In [23]:
Out = th.zeros_like(C)
for i in range(2):
    for j in range(2):
        Out[i,j] = (AK[i]@C[i,j]@AL[j])

In [24]:
Out

tensor([[[[0.0000, 0.0000],
          [0.0000, 0.0000]],

         [[1.0180, 0.9725],
          [1.4115, 1.3483]]],


        [[[2.4141, 3.0500],
          [2.5636, 3.2389]],

         [[3.2377, 3.0927],
          [3.4381, 3.2842]]]])

In [25]:
th.prod(th.diagonal(th.reshape(A, (2*2,2,2)), offset=0, dim1=-1, dim2=-2),-1)

tensor([0., 1., 4., 9.])

In [26]:
A

tensor([[[0., 0.],
         [0., 0.]],

        [[1., 1.],
         [1., 1.]],

        [[2., 2.],
         [2., 2.]],

        [[3., 3.],
         [3., 3.]]])

In [27]:
A.shape

torch.Size([4, 2, 2])

In [28]:
C.shape

torch.Size([2, 2, 2, 2])

In [29]:
AK = th.ones((3,2,2))
AK[1] = AK[1]*2
AK[2] = AK[2]*3
AK

tensor([[[1., 1.],
         [1., 1.]],

        [[2., 2.],
         [2., 2.]],

        [[3., 3.],
         [3., 3.]]])

In [30]:
AL = th.ones((3,2,2))*4
AL[1] = AL[1]+1
AL[2] = AL[2]+2
AL

tensor([[[4., 4.],
         [4., 4.]],

        [[5., 5.],
         [5., 5.]],

        [[6., 6.],
         [6., 6.]]])

In [31]:
AK = th.rand((3,2,2))
AL = th.rand((3,2,2))
nb = AK.shape[0]
AKL = th.zeros((nb,nb,2,2))
for i in range(nb):
    for j in range(nb):
        AKL[i,j] =  AK[i] + AL[j]
AKL

tensor([[[[0.3815, 0.8478],
          [0.9347, 1.3274]],

         [[0.6822, 0.9582],
          [1.0125, 0.8016]],

         [[0.7748, 0.9572],
          [0.4323, 0.9876]]],


        [[[0.4173, 0.1317],
          [1.5672, 1.5372]],

         [[0.7180, 0.2421],
          [1.6450, 1.0114]],

         [[0.8106, 0.2410],
          [1.0648, 1.1974]]],


        [[[0.3917, 0.1685],
          [0.8993, 0.8819]],

         [[0.6924, 0.2789],
          [0.9770, 0.3561]],

         [[0.7849, 0.2779],
          [0.3969, 0.5421]]]])

In [32]:
U = AL.repeat((3,1,1,1)) + th.transpose(AK.repeat((3,1,1,1)), 0,1)

In [33]:
AKL == U

tensor([[[[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]]],


        [[[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]]],


        [[[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]]]], dtype=torch.uint8)

In [34]:
invAKL = th.rand_like(AKL)
invAKL = th.matmul(th.transpose(invAKL, dim0=-1, dim1=-2),invAKL)

In [35]:
Tmat = th.zeros_like(invAKL)
for i in range(nb):
    for j in range(nb):
        Tmat[i,j] = (AK[i]@invAKL[i,j]@AL[j])

In [36]:
Umat =Tmat

In [37]:
Z = AL.repeat((3,1,1,1)) @ th.transpose(AK.repeat((3,1,1,1)), 0,1)
Z*invAKL

tensor([[[[0.0414, 0.0987],
          [0.2208, 0.3950]],

         [[0.1730, 0.2290],
          [0.1005, 0.1413]],

         [[0.1237, 0.2312],
          [0.0643, 0.3355]]],


        [[[0.0182, 0.0240],
          [0.4386, 0.7607]],

         [[0.2394, 0.0638],
          [0.1418, 0.0671]],

         [[0.3273, 0.0584],
          [0.1378, 0.0866]]],


        [[[0.0380, 0.0117],
          [0.1432, 0.1704]],

         [[0.0721, 0.0575],
          [0.1415, 0.1128]],

         [[0.0846, 0.0292],
          [0.0423, 0.0457]]]])

In [38]:
Tmat

tensor([[[[0.3964, 0.3698],
          [0.3858, 0.3595]],

         [[0.4828, 0.1494],
          [0.5206, 0.1611]],

         [[0.3714, 0.4523],
          [0.3595, 0.3832]]],


        [[[0.1578, 0.1757],
          [0.9730, 1.0836]],

         [[0.2053, 0.0635],
          [0.9914, 0.3067]],

         [[0.1886, 0.0881],
          [0.8546, 0.4214]]],


        [[[0.1622, 0.1603],
          [0.2063, 0.2011]],

         [[0.2748, 0.0850],
          [0.3525, 0.1090]],

         [[0.0987, 0.0809],
          [0.1307, 0.1031]]]])

In [39]:
#or i in range(nb):
#   #or j in range(nb):
#   Umat[i] =th.matmul(AK[i], th.matmul(invAKL,AL))

In [40]:
Bmat=th.matmul(invAKL,AL)

In [41]:
th.matmul(th.transpose(AK.repeat((3,1,1,1)), 0,1), th.matmul(invAKL,AL))

tensor([[[[0.3964, 0.3698],
          [0.3858, 0.3595]],

         [[0.4828, 0.1494],
          [0.5206, 0.1611]],

         [[0.3714, 0.4523],
          [0.3595, 0.3832]]],


        [[[0.1578, 0.1757],
          [0.9730, 1.0836]],

         [[0.2053, 0.0635],
          [0.9914, 0.3067]],

         [[0.1886, 0.0881],
          [0.8546, 0.4214]]],


        [[[0.1622, 0.1603],
          [0.2063, 0.2011]],

         [[0.2748, 0.0850],
          [0.3525, 0.1090]],

         [[0.0987, 0.0809],
          [0.1307, 0.1031]]]])

In [42]:
Tmat

tensor([[[[0.3964, 0.3698],
          [0.3858, 0.3595]],

         [[0.4828, 0.1494],
          [0.5206, 0.1611]],

         [[0.3714, 0.4523],
          [0.3595, 0.3832]]],


        [[[0.1578, 0.1757],
          [0.9730, 1.0836]],

         [[0.2053, 0.0635],
          [0.9914, 0.3067]],

         [[0.1886, 0.0881],
          [0.8546, 0.4214]]],


        [[[0.1622, 0.1603],
          [0.2063, 0.2011]],

         [[0.2748, 0.0850],
          [0.3525, 0.1090]],

         [[0.0987, 0.0809],
          [0.1307, 0.1031]]]])

In [43]:
Bmat.shape

torch.Size([3, 3, 2, 2])

In [44]:
Umat==Tmat

tensor([[[[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]]],


        [[[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]]],


        [[[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1]]]], dtype=torch.uint8)

In [45]:
Umat

tensor([[[[0.3964, 0.3698],
          [0.3858, 0.3595]],

         [[0.4828, 0.1494],
          [0.5206, 0.1611]],

         [[0.3714, 0.4523],
          [0.3595, 0.3832]]],


        [[[0.1578, 0.1757],
          [0.9730, 1.0836]],

         [[0.2053, 0.0635],
          [0.9914, 0.3067]],

         [[0.1886, 0.0881],
          [0.8546, 0.4214]]],


        [[[0.1622, 0.1603],
          [0.2063, 0.2011]],

         [[0.2748, 0.0850],
          [0.3525, 0.1090]],

         [[0.0987, 0.0809],
          [0.1307, 0.1031]]]])

In [46]:
A.shape

torch.Size([4, 2, 2])

In [49]:
th.set_printoptions(linewidth=120)
H = th.randn((10,10))
H

tensor([[-0.3638, -0.1201,  0.3904, -1.4934, -0.8096, -0.1392, -0.3428,  0.0456,  0.3476, -0.4315],
        [ 0.4068,  1.5212, -0.8504,  1.3791,  1.2256, -0.4538,  0.3660,  1.1759, -0.0253, -2.6509],
        [-0.3425,  0.4832, -0.1496,  1.3972,  0.7561,  1.2968,  0.3178,  1.2540,  0.3873,  1.0936],
        [-0.9202,  0.9885, -0.8722,  0.4117, -2.3096,  1.7204,  1.1650,  2.1419, -0.9111,  1.4020],
        [-0.8174, -1.8717, -1.3193,  0.5695,  0.7235,  0.4342, -0.4693, -0.1535,  0.2475, -1.1776],
        [-0.7913, -0.7075, -0.3443, -1.1532,  1.9757,  0.4977,  0.9649, -0.6405, -0.1854,  1.1997],
        [ 0.1188, -1.8054,  2.9271, -1.8209, -0.6896,  0.3508, -0.0597,  1.3657, -1.1877,  0.2918],
        [ 0.0395,  0.1639,  0.7788, -1.0374, -1.5233,  0.2798, -1.2222, -1.5146, -0.8351,  1.3840],
        [ 0.7851,  0.5199,  1.0050, -0.5020, -0.7747, -0.6284,  0.2575,  0.4014,  1.5295,  0.4689],
        [-0.5465,  0.0849, -0.6653,  0.9266,  0.0464, -0.2550,  0.0146,  0.2913,  0.0301, -0.0350]])

In [54]:
th.triu(H,1)+th.t(th.triu(H))

tensor([[-0.3638, -0.1201,  0.3904, -1.4934, -0.8096, -0.1392, -0.3428,  0.0456,  0.3476, -0.4315],
        [-0.1201,  1.5212, -0.8504,  1.3791,  1.2256, -0.4538,  0.3660,  1.1759, -0.0253, -2.6509],
        [ 0.3904, -0.8504, -0.1496,  1.3972,  0.7561,  1.2968,  0.3178,  1.2540,  0.3873,  1.0936],
        [-1.4934,  1.3791,  1.3972,  0.4117, -2.3096,  1.7204,  1.1650,  2.1419, -0.9111,  1.4020],
        [-0.8096,  1.2256,  0.7561, -2.3096,  0.7235,  0.4342, -0.4693, -0.1535,  0.2475, -1.1776],
        [-0.1392, -0.4538,  1.2968,  1.7204,  0.4342,  0.4977,  0.9649, -0.6405, -0.1854,  1.1997],
        [-0.3428,  0.3660,  0.3178,  1.1650, -0.4693,  0.9649, -0.0597,  1.3657, -1.1877,  0.2918],
        [ 0.0456,  1.1759,  1.2540,  2.1419, -0.1535, -0.6405,  1.3657, -1.5146, -0.8351,  1.3840],
        [ 0.3476, -0.0253,  0.3873, -0.9111,  0.2475, -0.1854, -1.1877, -0.8351,  1.5295,  0.4689],
        [-0.4315, -2.6509,  1.0936,  1.4020, -1.1776,  1.1997,  0.2918,  1.3840,  0.4689, -0.0350]])