In [1]:
import numpy as np
import torch as th

In [42]:
vechA=th.tensor([1.,2.,3.])

In [43]:
vechA

tensor([1., 2., 3.])

In [44]:
vechA.size()

torch.Size([3])

In [45]:
vechA.reshape(1,1)
vechA.size()

RuntimeError: shape '[1, 1]' is invalid for input of size 3

In [46]:
vechA.split(2,0)

(tensor([1., 2.]), tensor([3.]))

In [47]:
L=th.zeros(2,2)

In [48]:
L.copy_(vechA)

RuntimeError: The expanded size of the tensor (2) must match the existing size (3) at non-singleton dimension 1.  Target sizes: [2, 2].  Tensor sizes: [3]

In [49]:
vechA.expand(-1,2)

RuntimeError: The expanded size of the tensor (2) must match the existing size (3) at non-singleton dimension 1.  Target sizes: [-1, 2].  Tensor sizes: [3]

In [52]:
#L = th.tensor([[0,0],[0,0]])
L = th.zeros(2,2)
L.put_(th.tensor([0,1, 2]), vechA)

tensor([[1., 2.],
        [3., 0.]])

In [54]:
L.t()

tensor([[1., 3.],
        [2., 0.]])

In [37]:
th.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])