In [3]:
import tensorflow as tf
import numpy as np 
import time 
#import tensorflow.experimental.numpy as tnp
#import tensorflow_probability as tfp

In [6]:
tf.

AttributeError: module 'tensorflow' has no attribute '__version__'

In [16]:
n=3
nn=n*(n+1)/2

In [17]:
vechA=np.arange(nn)+1

In [18]:
vechA

array([1., 2., 3., 4., 5., 6.])

In [41]:
V=np.reshape(np.arange(12)+1, (2,6))

In [42]:
V

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [28]:
vechA

array([1., 2., 3., 4., 5., 6.])

In [53]:
ijl=np.triu_indices(3)
ijl

(array([0, 0, 0, 1, 1, 2]), array([0, 1, 2, 1, 2, 2]))

In [62]:
L = np.zeros((2,3,3))
L[...][ijl]=V[...]

ValueError: shape mismatch: value array of shape (2,6) could not be broadcast to indexing result of shape (6,3)

In [ ]:
M = np.resize((3,3), np.arange(12)+1)
print(M)

In [ ]:
def vech(A):
    
    v = zeros()